---

- name: Check if splunk package exists
  stat:
    path: "/tmp/{{ SPLUNK_PACKAGE }}"
  register: splunk_package_check

- name: Download splunk
  ansible.builtin.get_url:
    url: "{{ SPLUNK_URL }}"
    dest: "/tmp/{{ SPLUNK_PACKAGE }}"
  when: splunk_package_check.stat.exists == false

- name: Ensure splunk group exists with correct gid
  become: true
  ansible.builtin.group:
    name: "{{ SPLUNK_GROUP_NAME }}"
    state: present
    gid: "{{ SPLUNK_GROUP_GID }}"

- name: Add the splunk user to the splunk group
  become: true
  ansible.builtin.user:
    name: "{{ SPLUNK_ACCOUNT_NAME }}"
    comment: Splunk Developer
    uid: "{{ SPLUNK_ACCOUNT_UID }}"
    group: "{{ SPLUNK_GROUP_NAME }}"

- name: Extract splunk
  become: true
  ansible.builtin.unarchive:
    src: "/tmp/{{ SPLUNK_PACKAGE }}"
    dest: /opt
    creates: /opt/splunk

- name: Copy user-seed.conf
  become: true
  ansible.builtin.copy:
    src: user-seed.conf
    dest: /opt/splunk/etc/system/local/user-seed.conf

- name: Recursively change ownership of /opt/splunk
  become: true
  ansible.builtin.file:
    path: /opt/splunk
    state: directory
    recurse: yes
    owner: splunk-dev
    group: splunk-dev

- name: Start splunk for the first time
  become: true
  become_user: "{{ SPLUNK_ACCOUNT_NAME }}"
  ansible.builtin.command:
    cmd: /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt
    creates: /etc/systemd/system/Splunkd.service

- name: Stop splunk after the first start
  become: true
  become_user: "{{ SPLUNK_ACCOUNT_NAME }}"
  ansible.builtin.command:
    cmd: /opt/splunk/bin/splunk stop
    creates: /etc/systemd/system/Splunkd.service

- name: Enable boot-start
  become: true
  ansible.builtin.command:
    cmd: "/opt/splunk/bin/splunk enable boot-start -user {{ SPLUNK_ACCOUNT_NAME }} -systemd-managed 1"
    creates: /etc/systemd/system/Splunkd.service

- name: Open firewall (redhat)
  become: true
  ansible.builtin.command: "{{ item }}"
  with_items:
      - "firewall-cmd --zone=public --permanent --add-port=8000/tcp"
      - "firewall-cmd --reload"
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Ensure splunk service is running
  become: true
  ansible.builtin.systemd:
    name: Splunkd
    state: started
