---

- name: Include splunk apps variables
  ansible.builtin.include_vars:
    file: splunk.json
    name: splunk

- name: Debug
  ansible.builtin.debug:
    msg: "{{ debug_item }}"
  with_items:
    - "{{ splunk.SPLUNK }}"
    - "{{ splunk.SPLUNK_APPS|dict2items }}"
    - "{{ splunk.REPO_APPS|dict2items }}"
    - "{{ splunk.CUSTOM_APPS|dict2items }}"
  loop_control:
    loop_var: debug_item

- name: Install splunk
  include_tasks: "{{ splunk_item }}"
  with_items:
    - _cleanup.yml
    - splunk.yml
  loop_control:
    loop_var: splunk_item
