version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  standalone:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: splunk_standalone
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
    volumes:
      - './apps:/opt/splunk/etc/apps'
    networks:
      splunknet:
        aliases:
          - standalone
    ports:
      - 8000:8000
      - 8089:8089
