---

- name: Include splunk apps variables
  ansible.builtin.include_vars:
    file: ../SplunkResources/splunk.json
    name: splunk

- name: Debug
  ansible.builtin.debug:
    msg: "{{ debug_item }}"
  with_items:
    - "{{ splunk.SPLUNK }}"
    - "{{ splunk.SPLUNK_APPS|dict2items }}"
    - "{{ splunk.REPO_APPS|dict2items }}"
    - "{{ splunk.CUSTOM_APPS|dict2items }}"
  loop_control:
    loop_var: debug_item

- name: Ensure splunk group exists with correct gid
  become: true
  ansible.builtin.group:
    name: "{{ SPLUNK_GROUP_NAME }}"
    gid: "{{ SPLUNK_GROUP_GID }}"
    state: present

- name: Add the splunk user to the splunk group
  become: true
  ansible.builtin.user:
    name: "{{ SPLUNK_ACCOUNT_NAME }}"
    comment: Splunk Developer
    uid: "{{ SPLUNK_ACCOUNT_UID }}"
    group: "{{ SPLUNK_GROUP_NAME }}"
    shell: /bin/bash
