---

- name: Update apt-cache
  become: true
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade all packages to their latest version
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: ['ca-certificates', 'gnupg2', 'acl', 'python3-pip']
    state: present
    update_cache: yes
