---

- name: Upgrade all packages to their latest version
  become: true
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Install required packages
  become: true
  ansible.builtin.yum:
    name: ['yum-utils', 'unzip']
    state: present
