---

- name: Upgrade all packages to their latest version
  become: yes
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Install required packages
  become: yes
  ansible.builtin.yum:
    name: ['yum-utils', 'unzip']
    state: present
