---

- name: Update all packages to their latest version
  become: true
  ansible.builtin.dnf:
    name: '*'
    state: latest

- name: Install required packages
  become: true
  ansible.builtin.dnf:
    name: ['yum-utils', 'unzip']
    state: present
