---

- name: Stop splunk
  become: true
  ansible.builtin.command:
    cmd: /opt/splunk/bin/splunk stop
    removes: /opt/splunk/bin/splunk

- name: Remove splunk
  become: true
  ansible.builtin.file:
    path: "{{ remove_item }}"
    state: absent
  with_items:
    - /etc/init.d/splunk
    - /opt/splunk
  loop_control:
    loop_var: remove_item

- name: Extract splunk
  become: true
  ansible.builtin.unarchive:
    src: "../SplunkResources/{{ splunk.SPLUNK.src }}"
    dest: /opt
    creates: /opt/splunk

- name: Copy user-seed.conf
  become: true
  ansible.builtin.copy:
    src: user-seed.conf
    dest: /opt/splunk/etc/system/local/user-seed.conf

- name: Recursively change ownership of /opt/splunk
  become: true
  ansible.builtin.file:
    path: /opt/splunk
    state: directory
    recurse: yes
    owner: "{{ SPLUNK_ACCOUNT_NAME }}"
    group: "{{ SPLUNK_GROUP_NAME }}"

- name: Start splunk for the first time
  become: true
  become_user: "{{ SPLUNK_ACCOUNT_NAME }}"
  ansible.builtin.command:
    cmd: /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt
    creates: /etc/init.d/splunk

- name: Stop splunk after the first start
  become: true
  become_user: "{{ SPLUNK_ACCOUNT_NAME }}"
  ansible.builtin.command:
    cmd: /opt/splunk/bin/splunk stop
    creates: /etc/init.d/splunk

- name: Enable boot-start
  become: true
  ansible.builtin.command:
    cmd: "/opt/splunk/bin/splunk enable boot-start -user {{ SPLUNK_ACCOUNT_NAME }}"
    creates: /etc/init.d/splunk

- name: Open firewall (redhat)
  become: true
  ansible.builtin.command: "{{ item }}"
  with_items:
      - "firewall-cmd --zone=public --permanent --add-port=8000/tcp"
      - "firewall-cmd --zone=public --permanent --add-port=8089/tcp"
      - "firewall-cmd --reload"
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Set facts
  ansible.builtin.set_fact:
    SPLUNK_RESOURCES_DIR: ../SplunkResources
    SPLUNK_APPS_DIR: /opt/splunk/etc/apps

- name: Install apps
  ansible.builtin.import_role:
    name: splunk_apps

- name: Recursively change ownership of /opt/splunk
  become: true
  ansible.builtin.file:
    path: /opt/splunk
    state: directory
    recurse: yes
    owner: "{{ SPLUNK_ACCOUNT_NAME }}"
    group: "{{ SPLUNK_GROUP_NAME }}"

- name: Start splunk
  become: true
  become_user: "{{ SPLUNK_ACCOUNT_NAME }}"
  ansible.builtin.command:
    cmd: /opt/splunk/bin/splunk start
