---

- name: Download docker gpg key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: "{{ ansible_user_dir }}/docker.gpg"
    mode: '0440'
    force: yes

- name: De-armor gpg key
  ansible.builtin.shell: "gpg --dearmor < {{ ansible_user_dir }}/docker.gpg > {{ ansible_user_dir }}/docker-archive-keyring.gpg"
  become: true

- name: Install gpg key to /usr/share/keyrings/
  ansible.builtin.shell: "install -o root -g root -m 644 {{ ansible_user_dir }}/docker-archive-keyring.gpg /usr/share/keyrings/docker-archive-keyring.gpg"
  become: true

- name: Cleanup home directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_user_dir }}/docker.gpg"
    - "{{ ansible_user_dir }}/docker-archive-keyring.gpg"

- name: Configure docker repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    filename: docker
    state: present
    update_cache: yes
  become: true

- name: Install docker + containerd + docker-compose-plugin
  ansible.builtin.apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
    state: present
  become: true
