---

- name: Import tasks for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Import tasks for RHEL
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Ensure group "docker" exists with correct gid
  become: true
  ansible.builtin.group:
    name: docker
    state: present
    gid: 1750

- name: Add user to "docker" group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: ['docker']
    append: yes

- name: Start docker daemon
  become: true
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    name: docker

- name: Start containerd daemon
  become: true
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    name: containerd
