---

- hosts: ['localhost','all']
  vars:
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - include_tasks: playbooks/main.yml

  roles:
    - role: ansible_facts
    - role: splunk_common
    - role: splunk_local
