---

- name: Stop splunk
  become: true
  ansible.builtin.command:
    cmd: /opt/splunk/bin/splunk stop
    removes: /opt/splunk/bin/splunk

- name: Remove splunk service
  become: true
  ansible.builtin.file:
    path: "{{ remove_item }}"
    state: absent
  with_items:
    - /etc/init.d/splunk
    - /opt/splunk
  loop_control:
    loop_var: remove_item

- name: Remove the splunk user
  become: true
  ansible.builtin.user:
    name: "{{ SPLUNK_ACCOUNT_NAME }}"
    state: absent
    remove: yes

- name: Remove the splunk group
  become: true
  ansible.builtin.user:
    name: "{{ SPLUNK_GROUP_NAME }}"
    state: absent
